// this file was auto-generated by wrapit v0.1.0-54-g4322429
#include <type_traits>
#include "jlcxx/jlcxx.hpp"
#include "jlcxx/functions.hpp"
#include "jlcxx/stl.hpp"

#include "cpp/jlGeant4.h"


#ifdef VERBOSE_IMPORT
#  define DEBUG_MSG(a) std::cerr << a << "\n"
#else
#  define DEBUG_MSG(a)
#endif
#define __HERE__  __FILE__ ":" QUOTE2(__LINE__)
#define QUOTE(arg) #arg
#define QUOTE2(arg) QUOTE(arg)
void add_methods_for_G4Event(jlcxx::Module& types, jlcxx::TypeWrapper<G4Event>& t91) {


  /**********************************************************************/
  /* Wrappers for the methods of class G4Event
   */


  DEBUG_MSG("Adding wrapper for void G4Event::G4Event(G4int) (" __HERE__ ")");
  // defined in /Users/mato/.julia/artifacts/9d4b417a98ec8f720b8871baefe87108f864656f/include/Geant4/G4Event.hh:61:14
  t91.constructor<G4int>(/*finalize=*/true);
  types.set_override_module(jl_base_module);

  DEBUG_MSG("Adding wrapper for G4bool G4Event::operator==(const G4Event &) (" __HERE__ ")");
  // signature to use in the veto list: G4bool G4Event::operator==(const G4Event &)
  // defined in /Users/mato/.julia/artifacts/9d4b417a98ec8f720b8871baefe87108f864656f/include/Geant4/G4Event.hh:70:12
  t91.method("==", static_cast<G4bool (G4Event::*)(const G4Event &)  const>(&G4Event::operator==));

  DEBUG_MSG("Adding wrapper for G4bool G4Event::operator!=(const G4Event &) (" __HERE__ ")");
  // signature to use in the veto list: G4bool G4Event::operator!=(const G4Event &)
  // defined in /Users/mato/.julia/artifacts/9d4b417a98ec8f720b8871baefe87108f864656f/include/Geant4/G4Event.hh:71:12
  t91.method("!=", static_cast<G4bool (G4Event::*)(const G4Event &)  const>(&G4Event::operator!=));

  types.unset_override_module();

  DEBUG_MSG("Adding wrapper for void G4Event::Print() (" __HERE__ ")");
  // signature to use in the veto list: void G4Event::Print()
  // defined in /Users/mato/.julia/artifacts/9d4b417a98ec8f720b8871baefe87108f864656f/include/Geant4/G4Event.hh:73:10
  t91.method("Print", static_cast<void (G4Event::*)()  const>(&G4Event::Print));

  DEBUG_MSG("Adding wrapper for void G4Event::Draw() (" __HERE__ ")");
  // signature to use in the veto list: void G4Event::Draw()
  // defined in /Users/mato/.julia/artifacts/9d4b417a98ec8f720b8871baefe87108f864656f/include/Geant4/G4Event.hh:75:10
  t91.method("Draw", static_cast<void (G4Event::*)()  const>(&G4Event::Draw));

  DEBUG_MSG("Adding wrapper for void G4Event::SetEventID(G4int) (" __HERE__ ")");
  // signature to use in the veto list: void G4Event::SetEventID(G4int)
  // defined in /Users/mato/.julia/artifacts/9d4b417a98ec8f720b8871baefe87108f864656f/include/Geant4/G4Event.hh:80:17
  t91.method("SetEventID", static_cast<void (G4Event::*)(G4int) >(&G4Event::SetEventID));

  DEBUG_MSG("Adding wrapper for void G4Event::SetHCofThisEvent(G4HCofThisEvent *) (" __HERE__ ")");
  // signature to use in the veto list: void G4Event::SetHCofThisEvent(G4HCofThisEvent *)
  // defined in /Users/mato/.julia/artifacts/9d4b417a98ec8f720b8871baefe87108f864656f/include/Geant4/G4Event.hh:82:17
  t91.method("SetHCofThisEvent", static_cast<void (G4Event::*)(G4HCofThisEvent *) >(&G4Event::SetHCofThisEvent));

  DEBUG_MSG("Adding wrapper for void G4Event::SetDCofThisEvent(G4DCofThisEvent *) (" __HERE__ ")");
  // signature to use in the veto list: void G4Event::SetDCofThisEvent(G4DCofThisEvent *)
  // defined in /Users/mato/.julia/artifacts/9d4b417a98ec8f720b8871baefe87108f864656f/include/Geant4/G4Event.hh:84:17
  t91.method("SetDCofThisEvent", static_cast<void (G4Event::*)(G4DCofThisEvent *) >(&G4Event::SetDCofThisEvent));

  DEBUG_MSG("Adding wrapper for void G4Event::SetTrajectoryContainer(G4TrajectoryContainer *) (" __HERE__ ")");
  // signature to use in the veto list: void G4Event::SetTrajectoryContainer(G4TrajectoryContainer *)
  // defined in /Users/mato/.julia/artifacts/9d4b417a98ec8f720b8871baefe87108f864656f/include/Geant4/G4Event.hh:86:17
  t91.method("SetTrajectoryContainer", static_cast<void (G4Event::*)(G4TrajectoryContainer *) >(&G4Event::SetTrajectoryContainer));

  DEBUG_MSG("Adding wrapper for void G4Event::SetEventAborted() (" __HERE__ ")");
  // signature to use in the veto list: void G4Event::SetEventAborted()
  // defined in /Users/mato/.julia/artifacts/9d4b417a98ec8f720b8871baefe87108f864656f/include/Geant4/G4Event.hh:88:17
  t91.method("SetEventAborted", static_cast<void (G4Event::*)() >(&G4Event::SetEventAborted));

  DEBUG_MSG("Adding wrapper for void G4Event::SetRandomNumberStatus(G4String &) (" __HERE__ ")");
  // signature to use in the veto list: void G4Event::SetRandomNumberStatus(G4String &)
  // defined in /Users/mato/.julia/artifacts/9d4b417a98ec8f720b8871baefe87108f864656f/include/Geant4/G4Event.hh:90:17
  t91.method("SetRandomNumberStatus", static_cast<void (G4Event::*)(G4String &) >(&G4Event::SetRandomNumberStatus));

  DEBUG_MSG("Adding wrapper for void G4Event::SetRandomNumberStatusForProcessing(G4String &) (" __HERE__ ")");
  // signature to use in the veto list: void G4Event::SetRandomNumberStatusForProcessing(G4String &)
  // defined in /Users/mato/.julia/artifacts/9d4b417a98ec8f720b8871baefe87108f864656f/include/Geant4/G4Event.hh:95:17
  t91.method("SetRandomNumberStatusForProcessing", static_cast<void (G4Event::*)(G4String &) >(&G4Event::SetRandomNumberStatusForProcessing));

  DEBUG_MSG("Adding wrapper for void G4Event::KeepTheEvent(G4bool) (" __HERE__ ")");
  // signature to use in the veto list: void G4Event::KeepTheEvent(G4bool)
  // defined in /Users/mato/.julia/artifacts/9d4b417a98ec8f720b8871baefe87108f864656f/include/Geant4/G4Event.hh:100:17
  t91.method("KeepTheEvent", static_cast<void (G4Event::*)(G4bool) >(&G4Event::KeepTheEvent));
  t91.method("KeepTheEvent", [](G4Event& a)->void{ a.KeepTheEvent(); });
  t91.method("KeepTheEvent", [](G4Event* a)->void{ a->KeepTheEvent(); });

  DEBUG_MSG("Adding wrapper for G4bool G4Event::ToBeKept() (" __HERE__ ")");
  // signature to use in the veto list: G4bool G4Event::ToBeKept()
  // defined in /Users/mato/.julia/artifacts/9d4b417a98ec8f720b8871baefe87108f864656f/include/Geant4/G4Event.hh:102:19
  t91.method("ToBeKept", static_cast<G4bool (G4Event::*)()  const>(&G4Event::ToBeKept));

  DEBUG_MSG("Adding wrapper for void G4Event::KeepForPostProcessing() (" __HERE__ ")");
  // signature to use in the veto list: void G4Event::KeepForPostProcessing()
  // defined in /Users/mato/.julia/artifacts/9d4b417a98ec8f720b8871baefe87108f864656f/include/Geant4/G4Event.hh:104:17
  t91.method("KeepForPostProcessing", static_cast<void (G4Event::*)()  const>(&G4Event::KeepForPostProcessing));

  DEBUG_MSG("Adding wrapper for void G4Event::PostProcessingFinished() (" __HERE__ ")");
  // signature to use in the veto list: void G4Event::PostProcessingFinished()
  // defined in /Users/mato/.julia/artifacts/9d4b417a98ec8f720b8871baefe87108f864656f/include/Geant4/G4Event.hh:106:17
  t91.method("PostProcessingFinished", static_cast<void (G4Event::*)()  const>(&G4Event::PostProcessingFinished));

  DEBUG_MSG("Adding wrapper for G4int G4Event::GetNumberOfGrips() (" __HERE__ ")");
  // signature to use in the veto list: G4int G4Event::GetNumberOfGrips()
  // defined in /Users/mato/.julia/artifacts/9d4b417a98ec8f720b8871baefe87108f864656f/include/Geant4/G4Event.hh:115:18
  t91.method("GetNumberOfGrips", static_cast<G4int (G4Event::*)()  const>(&G4Event::GetNumberOfGrips));

  DEBUG_MSG("Adding wrapper for G4int G4Event::GetEventID() (" __HERE__ ")");
  // signature to use in the veto list: G4int G4Event::GetEventID()
  // defined in /Users/mato/.julia/artifacts/9d4b417a98ec8f720b8871baefe87108f864656f/include/Geant4/G4Event.hh:118:18
  t91.method("GetEventID", static_cast<G4int (G4Event::*)()  const>(&G4Event::GetEventID));

  DEBUG_MSG("Adding wrapper for void G4Event::AddPrimaryVertex(G4PrimaryVertex *) (" __HERE__ ")");
  // signature to use in the veto list: void G4Event::AddPrimaryVertex(G4PrimaryVertex *)
  // defined in /Users/mato/.julia/artifacts/9d4b417a98ec8f720b8871baefe87108f864656f/include/Geant4/G4Event.hh:121:17
  t91.method("AddPrimaryVertex", static_cast<void (G4Event::*)(G4PrimaryVertex *) >(&G4Event::AddPrimaryVertex));

  DEBUG_MSG("Adding wrapper for G4int G4Event::GetNumberOfPrimaryVertex() (" __HERE__ ")");
  // signature to use in the veto list: G4int G4Event::GetNumberOfPrimaryVertex()
  // defined in /Users/mato/.julia/artifacts/9d4b417a98ec8f720b8871baefe87108f864656f/include/Geant4/G4Event.hh:133:18
  t91.method("GetNumberOfPrimaryVertex", static_cast<G4int (G4Event::*)()  const>(&G4Event::GetNumberOfPrimaryVertex));

  DEBUG_MSG("Adding wrapper for G4PrimaryVertex * G4Event::GetPrimaryVertex(G4int) (" __HERE__ ")");
  // signature to use in the veto list: G4PrimaryVertex * G4Event::GetPrimaryVertex(G4int)
  // defined in /Users/mato/.julia/artifacts/9d4b417a98ec8f720b8871baefe87108f864656f/include/Geant4/G4Event.hh:137:31
  t91.method("GetPrimaryVertex", static_cast<G4PrimaryVertex * (G4Event::*)(G4int)  const>(&G4Event::GetPrimaryVertex));
  t91.method("GetPrimaryVertex", [](G4Event const& a)->G4PrimaryVertex *{ return a.GetPrimaryVertex(); });
  t91.method("GetPrimaryVertex", [](G4Event const* a)->G4PrimaryVertex *{ return a->GetPrimaryVertex(); });

  DEBUG_MSG("Adding wrapper for G4HCofThisEvent * G4Event::GetHCofThisEvent() (" __HERE__ ")");
  // signature to use in the veto list: G4HCofThisEvent * G4Event::GetHCofThisEvent()
  // defined in /Users/mato/.julia/artifacts/9d4b417a98ec8f720b8871baefe87108f864656f/include/Geant4/G4Event.hh:156:29
  t91.method("GetHCofThisEvent", static_cast<G4HCofThisEvent * (G4Event::*)()  const>(&G4Event::GetHCofThisEvent));

  DEBUG_MSG("Adding wrapper for G4DCofThisEvent * G4Event::GetDCofThisEvent() (" __HERE__ ")");
  // signature to use in the veto list: G4DCofThisEvent * G4Event::GetDCofThisEvent()
  // defined in /Users/mato/.julia/artifacts/9d4b417a98ec8f720b8871baefe87108f864656f/include/Geant4/G4Event.hh:158:29
  t91.method("GetDCofThisEvent", static_cast<G4DCofThisEvent * (G4Event::*)()  const>(&G4Event::GetDCofThisEvent));

  DEBUG_MSG("Adding wrapper for G4TrajectoryContainer * G4Event::GetTrajectoryContainer() (" __HERE__ ")");
  // signature to use in the veto list: G4TrajectoryContainer * G4Event::GetTrajectoryContainer()
  // defined in /Users/mato/.julia/artifacts/9d4b417a98ec8f720b8871baefe87108f864656f/include/Geant4/G4Event.hh:160:35
  t91.method("GetTrajectoryContainer", static_cast<G4TrajectoryContainer * (G4Event::*)()  const>(&G4Event::GetTrajectoryContainer));

  DEBUG_MSG("Adding wrapper for G4bool G4Event::IsAborted() (" __HERE__ ")");
  // signature to use in the veto list: G4bool G4Event::IsAborted()
  // defined in /Users/mato/.julia/artifacts/9d4b417a98ec8f720b8871baefe87108f864656f/include/Geant4/G4Event.hh:167:19
  t91.method("IsAborted", static_cast<G4bool (G4Event::*)()  const>(&G4Event::IsAborted));

  DEBUG_MSG("Adding wrapper for void G4Event::SetUserInformation(G4VUserEventInformation *) (" __HERE__ ")");
  // signature to use in the veto list: void G4Event::SetUserInformation(G4VUserEventInformation *)
  // defined in /Users/mato/.julia/artifacts/9d4b417a98ec8f720b8871baefe87108f864656f/include/Geant4/G4Event.hh:171:17
  t91.method("SetUserInformation", static_cast<void (G4Event::*)(G4VUserEventInformation *) >(&G4Event::SetUserInformation));

  DEBUG_MSG("Adding wrapper for G4VUserEventInformation * G4Event::GetUserInformation() (" __HERE__ ")");
  // signature to use in the veto list: G4VUserEventInformation * G4Event::GetUserInformation()
  // defined in /Users/mato/.julia/artifacts/9d4b417a98ec8f720b8871baefe87108f864656f/include/Geant4/G4Event.hh:173:37
  t91.method("GetUserInformation", static_cast<G4VUserEventInformation * (G4Event::*)()  const>(&G4Event::GetUserInformation));

  DEBUG_MSG("Adding wrapper for const G4String & G4Event::GetRandomNumberStatus() (" __HERE__ ")");
  // signature to use in the veto list: const G4String & G4Event::GetRandomNumberStatus()
  // defined in /Users/mato/.julia/artifacts/9d4b417a98ec8f720b8871baefe87108f864656f/include/Geant4/G4Event.hh:177:28
  t91.method("GetRandomNumberStatus", static_cast<const G4String & (G4Event::*)()  const>(&G4Event::GetRandomNumberStatus));

  DEBUG_MSG("Adding wrapper for const G4String & G4Event::GetRandomNumberStatusForProcessing() (" __HERE__ ")");
  // signature to use in the veto list: const G4String & G4Event::GetRandomNumberStatusForProcessing()
  // defined in /Users/mato/.julia/artifacts/9d4b417a98ec8f720b8871baefe87108f864656f/include/Geant4/G4Event.hh:185:28
  t91.method("GetRandomNumberStatusForProcessing", static_cast<const G4String & (G4Event::*)()  const>(&G4Event::GetRandomNumberStatusForProcessing));

  /* End of G4Event class method wrappers
   **********************************************************************/

}
