// this file was auto-generated by wrapit v1.6.0
#include "Wrapper.h"

#include "jlGeant4.h"
#include "dbg_msg.h"
#include "jlcxx/functions.hpp"
#include "jlcxx/stl.hpp"

namespace jlcxx {
  template<> struct IsMirroredType<G4IonisParamMat> : std::false_type { };
  template<> struct DefaultConstructible<G4IonisParamMat> : std::false_type { };
}

// Class generating the wrapper for type G4IonisParamMat
// signature to use in the veto file: G4IonisParamMat
struct JlG4IonisParamMat: public Wrapper {

  JlG4IonisParamMat(jlcxx::Module& jlModule): Wrapper(jlModule){
    DEBUG_MSG("Adding wrapper for type G4IonisParamMat (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/c08a070cdc1b892bb33db4924fdac1694e77d3a1/include/Geant4/G4IonisParamMat.hh:48:7
    jlcxx::TypeWrapper<G4IonisParamMat>  t = jlModule.add_type<G4IonisParamMat>("G4IonisParamMat");
    type_ = std::unique_ptr<jlcxx::TypeWrapper<G4IonisParamMat>>(new jlcxx::TypeWrapper<G4IonisParamMat>(jlModule, t));
  }

  void add_methods() const{
    auto& t = *type_;
  }

private:
  std::unique_ptr<jlcxx::TypeWrapper<G4IonisParamMat>> type_;
};
std::shared_ptr<Wrapper> newJlG4IonisParamMat(jlcxx::Module& module){
  return std::shared_ptr<Wrapper>(new JlG4IonisParamMat(module));
}
