// this file was auto-generated by wrapit 
#include "Wrapper.h"

#include "jlGeant4.h"
#include "dbg_msg.h"
#include "jlcxx/functions.hpp"
#include "jlcxx/stl.hpp"

namespace jlcxx {
  template<> struct IsMirroredType<G4TrajectoryContainer> : std::false_type { };
  template<> struct DefaultConstructible<G4TrajectoryContainer> : std::false_type { };
}

// Class generating the wrapper for type G4TrajectoryContainer
// signature to use in the veto file: G4TrajectoryContainer
struct JlG4TrajectoryContainer: public Wrapper {

  JlG4TrajectoryContainer(jlcxx::Module& jlModule): Wrapper(jlModule){
    DEBUG_MSG("Adding wrapper for type G4TrajectoryContainer (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afb5743b029965f72ec5a970d92d5344ce830d2/include/Geant4/G4TrajectoryContainer.hh:47:7
    jlcxx::TypeWrapper<G4TrajectoryContainer>  t = jlModule.add_type<G4TrajectoryContainer>("G4TrajectoryContainer");
    type_ = std::unique_ptr<jlcxx::TypeWrapper<G4TrajectoryContainer>>(new jlcxx::TypeWrapper<G4TrajectoryContainer>(jlModule, t));
  }

  void add_methods() const{
    auto& t = *type_;
    t.template constructor<>(/*finalize=*/true);
    module_.set_override_module(jl_base_module);

    DEBUG_MSG("Adding wrapper for G4bool G4TrajectoryContainer::operator==(const G4TrajectoryContainer &) (" __HERE__ ")");
    // signature to use in the veto list: G4bool G4TrajectoryContainer::operator==(const G4TrajectoryContainer &)
    // defined in /Users/mato/.julia/artifacts/4afb5743b029965f72ec5a970d92d5344ce830d2/include/Geant4/G4TrajectoryContainer.hh:60:12
    t.method("==", static_cast<G4bool (G4TrajectoryContainer::*)(const G4TrajectoryContainer &)  const>(&G4TrajectoryContainer::operator==));

    DEBUG_MSG("Adding wrapper for G4bool G4TrajectoryContainer::operator!=(const G4TrajectoryContainer &) (" __HERE__ ")");
    // signature to use in the veto list: G4bool G4TrajectoryContainer::operator!=(const G4TrajectoryContainer &)
    // defined in /Users/mato/.julia/artifacts/4afb5743b029965f72ec5a970d92d5344ce830d2/include/Geant4/G4TrajectoryContainer.hh:61:12
    t.method("!=", static_cast<G4bool (G4TrajectoryContainer::*)(const G4TrajectoryContainer &)  const>(&G4TrajectoryContainer::operator!=));

    module_.unset_override_module();

    DEBUG_MSG("Adding wrapper for size_t G4TrajectoryContainer::size() (" __HERE__ ")");
    // signature to use in the veto list: size_t G4TrajectoryContainer::size()
    // defined in /Users/mato/.julia/artifacts/4afb5743b029965f72ec5a970d92d5344ce830d2/include/Geant4/G4TrajectoryContainer.hh:63:24
    t.method("size", static_cast<size_t (G4TrajectoryContainer::*)()  const>(&G4TrajectoryContainer::size));

    DEBUG_MSG("Adding wrapper for void G4TrajectoryContainer::push_back(G4VTrajectory *) (" __HERE__ ")");
    // signature to use in the veto list: void G4TrajectoryContainer::push_back(G4VTrajectory *)
    // defined in /Users/mato/.julia/artifacts/4afb5743b029965f72ec5a970d92d5344ce830d2/include/Geant4/G4TrajectoryContainer.hh:64:17
    t.method("push_back", static_cast<void (G4TrajectoryContainer::*)(G4VTrajectory *) >(&G4TrajectoryContainer::push_back));

    DEBUG_MSG("Adding wrapper for size_t G4TrajectoryContainer::entries() (" __HERE__ ")");
    // signature to use in the veto list: size_t G4TrajectoryContainer::entries()
    // defined in /Users/mato/.julia/artifacts/4afb5743b029965f72ec5a970d92d5344ce830d2/include/Geant4/G4TrajectoryContainer.hh:65:24
    t.method("entries", static_cast<size_t (G4TrajectoryContainer::*)()  const>(&G4TrajectoryContainer::entries));

    DEBUG_MSG("Adding wrapper for G4bool G4TrajectoryContainer::insert(G4VTrajectory *) (" __HERE__ ")");
    // signature to use in the veto list: G4bool G4TrajectoryContainer::insert(G4VTrajectory *)
    // defined in /Users/mato/.julia/artifacts/4afb5743b029965f72ec5a970d92d5344ce830d2/include/Geant4/G4TrajectoryContainer.hh:66:19
    t.method("insert", static_cast<G4bool (G4TrajectoryContainer::*)(G4VTrajectory *) >(&G4TrajectoryContainer::insert));

    DEBUG_MSG("Adding wrapper for void G4TrajectoryContainer::clearAndDestroy() (" __HERE__ ")");
    // signature to use in the veto list: void G4TrajectoryContainer::clearAndDestroy()
    // defined in /Users/mato/.julia/artifacts/4afb5743b029965f72ec5a970d92d5344ce830d2/include/Geant4/G4TrajectoryContainer.hh:67:17
    t.method("clearAndDestroy", static_cast<void (G4TrajectoryContainer::*)() >(&G4TrajectoryContainer::clearAndDestroy));
    module_.set_override_module(jl_base_module);


    DEBUG_MSG("Adding getindex method to wrap G4VTrajectory * G4TrajectoryContainer::operator[](size_t) (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afb5743b029965f72ec5a970d92d5344ce830d2/include/Geant4/G4TrajectoryContainer.hh:72:27
    t.method("getindex",
      [](G4TrajectoryContainer& a, size_t i){
      return a[i];
    });

    module_.unset_override_module();

    DEBUG_MSG("Adding wrapper for TrajectoryVector * G4TrajectoryContainer::GetVector() (" __HERE__ ")");
    // signature to use in the veto list: TrajectoryVector * G4TrajectoryContainer::GetVector()
    // defined in /Users/mato/.julia/artifacts/4afb5743b029965f72ec5a970d92d5344ce830d2/include/Geant4/G4TrajectoryContainer.hh:73:30
    t.method("GetVector", static_cast<TrajectoryVector * (G4TrajectoryContainer::*)()  const>(&G4TrajectoryContainer::GetVector));
  }

private:
  std::unique_ptr<jlcxx::TypeWrapper<G4TrajectoryContainer>> type_;
};
std::shared_ptr<Wrapper> newJlG4TrajectoryContainer(jlcxx::Module& module){
  return std::shared_ptr<Wrapper>(new JlG4TrajectoryContainer(module));
}
