// this file was auto-generated by wrapit 5168a24-dirty
#include "Wrapper.h"

#include "jlGeant4.h"
#include "dbg_msg.h"
#include "jlcxx/functions.hpp"
#include "jlcxx/stl.hpp"

namespace jlcxx {
  template<> struct IsMirroredType<G4VScoringMesh> : std::false_type { };
  template<> struct DefaultConstructible<G4VScoringMesh> : std::false_type { };
}

// Class generating the wrapper for type G4VScoringMesh
// signature to use in the veto file: G4VScoringMesh
struct JlG4VScoringMesh: public Wrapper {

  JlG4VScoringMesh(jlcxx::Module& jlModule): Wrapper(jlModule){
    DEBUG_MSG("Adding wrapper for type G4VScoringMesh (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/04a1f392c53fa9913a6e32dc79e45dcf6f1dd250/include/Geant4/G4VScoringMesh.hh:54:7
    jlcxx::TypeWrapper<G4VScoringMesh>  t = jlModule.add_type<G4VScoringMesh>("G4VScoringMesh");
    type_ = std::unique_ptr<jlcxx::TypeWrapper<G4VScoringMesh>>(new jlcxx::TypeWrapper<G4VScoringMesh>(jlModule, t));
  }

  void add_methods() const{
    auto& t = *type_;
  }

private:
  std::unique_ptr<jlcxx::TypeWrapper<G4VScoringMesh>> type_;
};
std::shared_ptr<Wrapper> newJlG4VScoringMesh(jlcxx::Module& module){
  return std::shared_ptr<Wrapper>(new JlG4VScoringMesh(module));
}
