// this file was auto-generated by wrapit 5168a24-dirty
#include "Wrapper.h"

#include "jlGeant4.h"
#include "dbg_msg.h"
#include "jlcxx/functions.hpp"
#include "jlcxx/stl.hpp"

namespace jlcxx {
  template<> struct IsMirroredType<G4UserWorkerInitialization> : std::false_type { };
  template<> struct DefaultConstructible<G4UserWorkerInitialization> : std::false_type { };
}

// Class generating the wrapper for type G4UserWorkerInitialization
// signature to use in the veto file: G4UserWorkerInitialization
struct JlG4UserWorkerInitialization: public Wrapper {

  JlG4UserWorkerInitialization(jlcxx::Module& jlModule): Wrapper(jlModule){
    DEBUG_MSG("Adding wrapper for type G4UserWorkerInitialization (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/04a1f392c53fa9913a6e32dc79e45dcf6f1dd250/include/Geant4/G4UserWorkerInitialization.hh:65:7
    jlcxx::TypeWrapper<G4UserWorkerInitialization>  t = jlModule.add_type<G4UserWorkerInitialization>("G4UserWorkerInitialization");
    type_ = std::unique_ptr<jlcxx::TypeWrapper<G4UserWorkerInitialization>>(new jlcxx::TypeWrapper<G4UserWorkerInitialization>(jlModule, t));
  }

  void add_methods() const{
    auto& t = *type_;
    t.template constructor<>(/*finalize=*/jlcxx::finalize_policy::yes);

    DEBUG_MSG("Adding wrapper for void G4UserWorkerInitialization::WorkerInitialize() (" __HERE__ ")");
    // signature to use in the veto list: void G4UserWorkerInitialization::WorkerInitialize()
    // defined in /Users/mato/.julia/artifacts/04a1f392c53fa9913a6e32dc79e45dcf6f1dd250/include/Geant4/G4UserWorkerInitialization.hh:73:18
    t.method("WorkerInitialize", static_cast<void (G4UserWorkerInitialization::*)()  const>(&G4UserWorkerInitialization::WorkerInitialize));

    DEBUG_MSG("Adding wrapper for void G4UserWorkerInitialization::WorkerStart() (" __HERE__ ")");
    // signature to use in the veto list: void G4UserWorkerInitialization::WorkerStart()
    // defined in /Users/mato/.julia/artifacts/04a1f392c53fa9913a6e32dc79e45dcf6f1dd250/include/Geant4/G4UserWorkerInitialization.hh:79:18
    t.method("WorkerStart", static_cast<void (G4UserWorkerInitialization::*)()  const>(&G4UserWorkerInitialization::WorkerStart));

    DEBUG_MSG("Adding wrapper for void G4UserWorkerInitialization::WorkerRunStart() (" __HERE__ ")");
    // signature to use in the veto list: void G4UserWorkerInitialization::WorkerRunStart()
    // defined in /Users/mato/.julia/artifacts/04a1f392c53fa9913a6e32dc79e45dcf6f1dd250/include/Geant4/G4UserWorkerInitialization.hh:85:18
    t.method("WorkerRunStart", static_cast<void (G4UserWorkerInitialization::*)()  const>(&G4UserWorkerInitialization::WorkerRunStart));

    DEBUG_MSG("Adding wrapper for void G4UserWorkerInitialization::WorkerRunEnd() (" __HERE__ ")");
    // signature to use in the veto list: void G4UserWorkerInitialization::WorkerRunEnd()
    // defined in /Users/mato/.julia/artifacts/04a1f392c53fa9913a6e32dc79e45dcf6f1dd250/include/Geant4/G4UserWorkerInitialization.hh:89:18
    t.method("WorkerRunEnd", static_cast<void (G4UserWorkerInitialization::*)()  const>(&G4UserWorkerInitialization::WorkerRunEnd));

    DEBUG_MSG("Adding wrapper for void G4UserWorkerInitialization::WorkerStop() (" __HERE__ ")");
    // signature to use in the veto list: void G4UserWorkerInitialization::WorkerStop()
    // defined in /Users/mato/.julia/artifacts/04a1f392c53fa9913a6e32dc79e45dcf6f1dd250/include/Geant4/G4UserWorkerInitialization.hh:93:18
    t.method("WorkerStop", static_cast<void (G4UserWorkerInitialization::*)()  const>(&G4UserWorkerInitialization::WorkerStop));
  }

private:
  std::unique_ptr<jlcxx::TypeWrapper<G4UserWorkerInitialization>> type_;
};
std::shared_ptr<Wrapper> newJlG4UserWorkerInitialization(jlcxx::Module& module){
  return std::shared_ptr<Wrapper>(new JlG4UserWorkerInitialization(module));
}
