// this file was auto-generated by wrapit v1.3.1-15-g5168a24
#include "Wrapper.h"

#include "jlGeant4.h"
#include "dbg_msg.h"
#include "jlcxx/functions.hpp"
#include "jlcxx/stl.hpp"

namespace jlcxx {
  template<> struct IsMirroredType<G4GDMLReadStructure> : std::false_type { };
  template<> struct DefaultConstructible<G4GDMLReadStructure> : std::false_type { };
}

// Class generating the wrapper for type G4GDMLReadStructure
// signature to use in the veto file: G4GDMLReadStructure
struct JlG4GDMLReadStructure: public Wrapper {

  JlG4GDMLReadStructure(jlcxx::Module& jlModule): Wrapper(jlModule){
    DEBUG_MSG("Adding wrapper for type G4GDMLReadStructure (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/c08a070cdc1b892bb33db4924fdac1694e77d3a1/include/Geant4/G4GDMLReadStructure.hh:51:7
    jlcxx::TypeWrapper<G4GDMLReadStructure>  t = jlModule.add_type<G4GDMLReadStructure>("G4GDMLReadStructure");
    type_ = std::unique_ptr<jlcxx::TypeWrapper<G4GDMLReadStructure>>(new jlcxx::TypeWrapper<G4GDMLReadStructure>(jlModule, t));
  }

  void add_methods() const{
    auto& t = *type_;
    t.template constructor<>(/*finalize=*/jlcxx::finalize_policy::yes);
  }

private:
  std::unique_ptr<jlcxx::TypeWrapper<G4GDMLReadStructure>> type_;
};
std::shared_ptr<Wrapper> newJlG4GDMLReadStructure(jlcxx::Module& module){
  return std::shared_ptr<Wrapper>(new JlG4GDMLReadStructure(module));
}
