// this file was auto-generated by wrapit v1.3.1-15-g5168a24
#include "Wrapper.h"

#include "jlGeant4.h"
#include "dbg_msg.h"
#include "jlcxx/functions.hpp"
#include "jlcxx/stl.hpp"

namespace jlcxx {
  template<> struct IsMirroredType<G4VTrajectoryPoint> : std::false_type { };
  template<> struct DefaultConstructible<G4VTrajectoryPoint> : std::false_type { };
}

// Class generating the wrapper for type G4VTrajectoryPoint
// signature to use in the veto file: G4VTrajectoryPoint
struct JlG4VTrajectoryPoint: public Wrapper {

  JlG4VTrajectoryPoint(jlcxx::Module& jlModule): Wrapper(jlModule){
    DEBUG_MSG("Adding wrapper for type G4VTrajectoryPoint (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/c08a070cdc1b892bb33db4924fdac1694e77d3a1/include/Geant4/G4VTrajectoryPoint.hh:50:7
    jlcxx::TypeWrapper<G4VTrajectoryPoint>  t = jlModule.add_type<G4VTrajectoryPoint>("G4VTrajectoryPoint");
    type_ = std::unique_ptr<jlcxx::TypeWrapper<G4VTrajectoryPoint>>(new jlcxx::TypeWrapper<G4VTrajectoryPoint>(jlModule, t));
  }

  void add_methods() const{
    auto& t = *type_;
    module_.set_override_module(jl_base_module);

    DEBUG_MSG("Adding wrapper for G4bool G4VTrajectoryPoint::operator==(const G4VTrajectoryPoint &) (" __HERE__ ")");
    // signature to use in the veto list: G4bool G4VTrajectoryPoint::operator==(const G4VTrajectoryPoint &)
    // defined in /Users/mato/.julia/artifacts/c08a070cdc1b892bb33db4924fdac1694e77d3a1/include/Geant4/G4VTrajectoryPoint.hh:58:10
    t.method("==", static_cast<G4bool (G4VTrajectoryPoint::*)(const G4VTrajectoryPoint &)  const>(&G4VTrajectoryPoint::operator==));

    module_.unset_override_module();

    DEBUG_MSG("Adding wrapper for const G4ThreeVector G4VTrajectoryPoint::GetPosition() (" __HERE__ ")");
    // signature to use in the veto list: const G4ThreeVector G4VTrajectoryPoint::GetPosition()
    // defined in /Users/mato/.julia/artifacts/c08a070cdc1b892bb33db4924fdac1694e77d3a1/include/Geant4/G4VTrajectoryPoint.hh:61:31
    t.method("GetPosition", static_cast<const G4ThreeVector (G4VTrajectoryPoint::*)()  const>(&G4VTrajectoryPoint::GetPosition));

    DEBUG_MSG("Adding wrapper for const std::vector<G4ThreeVector> * G4VTrajectoryPoint::GetAuxiliaryPoints() (" __HERE__ ")");
    // signature to use in the veto list: const std::vector<G4ThreeVector> * G4VTrajectoryPoint::GetAuxiliaryPoints()
    // defined in /Users/mato/.julia/artifacts/c08a070cdc1b892bb33db4924fdac1694e77d3a1/include/Geant4/G4VTrajectoryPoint.hh:68:45
    t.method("GetAuxiliaryPoints", static_cast<const std::vector<G4ThreeVector> * (G4VTrajectoryPoint::*)()  const>(&G4VTrajectoryPoint::GetAuxiliaryPoints));

    DEBUG_MSG("Adding wrapper for std::vector<G4AttValue> * G4VTrajectoryPoint::CreateAttValues() (" __HERE__ ")");
    // signature to use in the veto list: std::vector<G4AttValue> * G4VTrajectoryPoint::CreateAttValues()
    // defined in /Users/mato/.julia/artifacts/c08a070cdc1b892bb33db4924fdac1694e77d3a1/include/Geant4/G4VTrajectoryPoint.hh:86:36
    t.method("CreateAttValues", static_cast<std::vector<G4AttValue> * (G4VTrajectoryPoint::*)()  const>(&G4VTrajectoryPoint::CreateAttValues));
  }

private:
  std::unique_ptr<jlcxx::TypeWrapper<G4VTrajectoryPoint>> type_;
};
std::shared_ptr<Wrapper> newJlG4VTrajectoryPoint(jlcxx::Module& module){
  return std::shared_ptr<Wrapper>(new JlG4VTrajectoryPoint(module));
}
