// this file was auto-generated by wrapit v1.6.0
#include "Wrapper.h"

#include "jlGeant4.h"
#include "dbg_msg.h"
#include "jlcxx/functions.hpp"
#include "jlcxx/stl.hpp"

namespace jlcxx {
  template<> struct IsMirroredType<G4PolyconeHistorical> : std::false_type { };
  template<> struct DefaultConstructible<G4PolyconeHistorical> : std::false_type { };
}

// Class generating the wrapper for type G4PolyconeHistorical
// signature to use in the veto file: G4PolyconeHistorical
struct JlG4PolyconeHistorical: public Wrapper {

  JlG4PolyconeHistorical(jlcxx::Module& jlModule): Wrapper(jlModule){
    DEBUG_MSG("Adding wrapper for type G4PolyconeHistorical (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/40f6fc0de669f0d3e0a749c73a29fe79804135d5/include/Geant4/G4PolyconeHistorical.hh:39:7
    jlcxx::TypeWrapper<G4PolyconeHistorical>  t = jlModule.add_type<G4PolyconeHistorical>("G4PolyconeHistorical");
    type_ = std::unique_ptr<jlcxx::TypeWrapper<G4PolyconeHistorical>>(new jlcxx::TypeWrapper<G4PolyconeHistorical>(jlModule, t));
  }

  void add_methods() const{
    auto& t = *type_;
    t.template constructor<>(/*finalize=*/jlcxx::finalize_policy::yes    );
  }

private:
  std::unique_ptr<jlcxx::TypeWrapper<G4PolyconeHistorical>> type_;
};
std::shared_ptr<Wrapper> newJlG4PolyconeHistorical(jlcxx::Module& module){
  return std::shared_ptr<Wrapper>(new JlG4PolyconeHistorical(module));
}
