// this file was auto-generated by wrapit v1.6.0
#include "Wrapper.h"

#include "jlGeant4.h"
#include "dbg_msg.h"
#include "jlcxx/functions.hpp"
#include "jlcxx/stl.hpp"

namespace jlcxx {
  template<> struct IsMirroredType<HepGeom::ReflectZ3D> : std::false_type { };
  template<> struct DefaultConstructible<HepGeom::ReflectZ3D> : std::false_type { };
template<> struct SuperType<HepGeom::ReflectZ3D> { typedef HepGeom::Reflect3D type; };
}

// Class generating the wrapper for type HepGeom::ReflectZ3D
// signature to use in the veto file: HepGeom::ReflectZ3D
struct JlHepGeom_ReflectZ3D: public Wrapper {

  JlHepGeom_ReflectZ3D(jlcxx::Module& jlModule): Wrapper(jlModule){
    DEBUG_MSG("Adding wrapper for type HepGeom::ReflectZ3D (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/c08a070cdc1b892bb33db4924fdac1694e77d3a1/include/Geant4/CLHEP/Geometry/Transform3D.h:698:9
    jlcxx::TypeWrapper<HepGeom::ReflectZ3D>  t = jlModule.add_type<HepGeom::ReflectZ3D>("HepGeom!ReflectZ3D",
      jlcxx::julia_base_type<HepGeom::Reflect3D>());
    type_ = std::unique_ptr<jlcxx::TypeWrapper<HepGeom::ReflectZ3D>>(new jlcxx::TypeWrapper<HepGeom::ReflectZ3D>(jlModule, t));
  }

  void add_methods() const{
    auto& t = *type_;
    t.template constructor<>(/*finalize=*/jlcxx::finalize_policy::yes    );


    DEBUG_MSG("Adding wrapper for void HepGeom::ReflectZ3D::ReflectZ3D(double) (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/c08a070cdc1b892bb33db4924fdac1694e77d3a1/include/Geant4/CLHEP/Geometry/Transform3D.h:702:5
    t.constructor<double>(/*finalize=*/jlcxx::finalize_policy::yes, jlcxx::arg("this"), jlcxx::arg("z")    );
  }

private:
  std::unique_ptr<jlcxx::TypeWrapper<HepGeom::ReflectZ3D>> type_;
};
std::shared_ptr<Wrapper> newJlHepGeom_ReflectZ3D(jlcxx::Module& module){
  return std::shared_ptr<Wrapper>(new JlHepGeom_ReflectZ3D(module));
}
